name: flutter_todo
description: "A new Flutter project."

# Este campo indica que o pacote não deve ser publicado no pub.dev
publish_to: 'none'

# Versão do app
version: 1.0.0+1

environment:
  # Define a versão mínima do SDK Dart necessária
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter  # SDK principal do Flutter

  cupertino_icons: ^1.0.8  # Ícones estilo iOS (Cupertino)

  material_color_utilities: ^0.11.1  # Utilitários para gerar paletas de cores dinâmicas (Material You)

  dio: ^5.8.0+1  # Cliente HTTP avançado (requisições REST, upload, interceptors)

  go_router: ^15.2.4  # Gerenciamento de rotas e navegação declarativa

  shared_preferences: ^2.5.3  # Armazenamento local simples (chave/valor)

  json_annotation: ^4.9.0  # Anotações para gerar código de serialização JSON

  path: ^1.8.3  # Manipulação de caminhos de arquivos e diretórios

  mime: ^1.0.4  # Detecção de tipos MIME de arquivos (ex.: image/png)

  image_picker: ^1.1.2  # Permite selecionar imagens da galeria ou tirar fotos

dev_dependencies:
  flutter_test:
    sdk: flutter  # Framework de testes unitários e de widget do Flutter

  flutter_lints: ^5.0.0  # Regras de lint recomendadas (boas práticas de código)

  build_runner: ^2.4.6  # Ferramenta que executa geradores de código (ex.: json_serializable)

  json_serializable: ^6.9.5  # Gerador de métodos fromJson/toJson automaticamente

flutter:
  uses-material-design: true  # Inclui fontes e ícones padrão do Material Design
